import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="bg-black flex flex-col">
        <Navbar />
        {children}
        <footer className="bg-black text-white text-center py-6">
          <p>
            &copy; {new Date().getFullYear()} Meu Portfólio. Todos os direitos
            reservados.
          </p>
        </footer>
      </body>
    </html>
  );
}
